#!/bin/bash

jsonArray() {
	local arr=($@)
	local arrlen=${#arr[@]}
	local i=0

	local output='['

	for x in "${arr[@]}"
	do
		i=$((${i} + 1))
		output+="$x"
		if [ $i != $arrlen ]; then
			output+=','
		fi
	done

	output+=']'

	echo $output
}

jsonObject() {
	local arr=($@)
	local arrlen=${#arr[@]}
	local i=0

	local output='{'

	for x in "${arr[@]}"
	do
		i=$((${i} + 1))
		output+="$x"
		if [ $i != $arrlen ]; then
			output+=','
		fi
	done

	output+='}'

	echo $output
}

createKeyVal() {
	echo '"'$1'":"'$2'"'
}

# START

ITEMS=()

##
## Music
##

# Spotify primary
MUSIC=`osascript ./osx-menubar/scripts/spotify-current-track`
MUSIC_SRC=''
if [[ -n "${MUSIC}" ]]; then
	MUSIC_SRC='spotify'
else
	# Sonos
	MUSIC=`./osx-menubar/scripts/sonos-current-track`
	[[ -n "${MUSIC}" ]] && MUSIC_SRC='sonos'
fi

ITEMS+=(`jsonObject $(createKeyVal 'target' 'music') $(createKeyVal 'value' "$MUSIC")`)

##
## Focused window
##

FOCUSED_WINDOW=`/usr/local/bin/kwmc query space active tag | sed -n -E 's/^\[[a-z]+\]\ ([a-zA-Z\ ]+).*/\1/p'`

ITEMS+=(`jsonObject $(createKeyVal 'target' 'focused_window') $(createKeyVal 'value' "$FOCUSED_WINDOW")`)

##
## Network
##

VPN=`osascript ./osx-menubar/scripts/network-vpn-viscocity`

ITEMS+=(`jsonObject $(createKeyVal 'target' 'vpn') $(createKeyVal 'value' "$VPN")`)

##
## Volume
##

AUDIO_VOLUME=`./osx-menubar/scripts/audio-volume`
if [ $AUDIO_VOLUME -gt 60 ]; then
	AUDIO_VOLUME_STATE='high'
elif [ $AUDIO_VOLUME -gt 30 ]; then
	AUDIO_VOLUME_STATE='medium'
elif [ $AUDIO_VOLUME -gt 0 ]; then
	AUDIO_VOLUME_STATE='low'
else
	AUDIO_VOLUME_STATE='mute'
fi

ITEMS+=(`jsonObject $(createKeyVal 'target' 'audio_volume') $(createKeyVal 'value' "$AUDIO_VOLUME") $(createKeyVal 'state' "$AUDIO_VOLUME_STATE")`)

##
## Battery
##

BATTERY=`./osx-menubar/scripts/battery-level`
if [ $BATTERY == 100 ]; then
	BATTERY_STATE='charged'
elif [ $BATTERY -gt 60 ]; then
	BATTERY_STATE='high'
elif [ $BATTERY -gt 30 ]; then
	BATTERY_STATE='medium'
elif [ $BATTERY -gt 20 ]; then
	BATTERY_STATE='low'
elif [ $BATTERY -gt 0 ]; then
	BATTERY_STATE='critical'
else
	$BATTERY_STATE='unknown'
fi

ITEMS+=(`jsonObject $(createKeyVal 'target' 'battery') $(createKeyVal 'value' "$BATTERY") $(createKeyVal 'state' "$BATTERY_STATE")`)

##
## Date
##

DATE=`date +"%d-%m-%Y"`

ITEMS+=(`jsonObject $(createKeyVal 'target' 'date') $(createKeyVal 'value' "$DATE")`)

##
## TIME
##

TIME=`date +"%H:%M"`

ITEMS+=(`jsonObject $(createKeyVal 'target' 'time') $(createKeyVal 'value' "$TIME")`)

echo `jsonArray ${ITEMS[@]}`

# END
