#!/usr/local/bin/python

deviceip=""

# Exit if no device IP is set
if len(deviceip) == 0:
	exit()

# Make sure device is ping able
import os

hostname=deviceip
response = os.system("ping -t 1 -c 1 "+deviceip+" > /dev/null && echo 1")

# If not, exit
if response != 1:
	exit()

# Make sure SoCo is available
try:
	from soco import SoCo
except ImportError, e:
	exit()

# Get device and track info
device = SoCo(deviceip)

track = device.get_current_track_info()
info = device.get_current_transport_info()

# Create output
song = track['artist']+' - '+track['title']

if info['current_transport_state'] == 'PLAYING':
	print song.encode(encoding='UTF-8',errors='strict')
